[package]
name = "CoolKinectVrThingy"
version = "0.1.0"
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termios = "0.3.3"
libc = "0.2.98"
libc-stdhandle = "0.1.0"
mem_cmp = "0.1.4"
